```{r figure_01, fig.height=250/96, fig.cap="**Figure 1**: Average 5'UTR, CDS, and 3'UTR lengths across all development stages."}
# Summary of gene structure
utr5_summary <- utr5_stats_filtered %>% 
	group_by(stage) %>% 
	summarise(median=median(length, na.rm=TRUE))

utr3_summary <- utr3_stats_filtered %>% 
	group_by(stage) %>% 
	summarise(median=median(length, na.rm=TRUE))

polypyrimidine_tracts <- polypyrimidine_tracts %>%
    mutate(length=end - start)
pp_tract_summary <- polypyrimidine_tracts %>%
    group_by(stage) %>% 
    summarise(median=median(length, na.rm=TRUE))

median_5utr <- (utr5_summary %>% filter(stage == 'combined'))$median
median_cds  <- median(as.numeric(genes$size))
median_3utr <- (utr3_summary %>% filter(stage == 'combined'))$median
median_ppt  <- (pp_tract_summary %>% filter(stage == 'combined'))$median

plot_gene_structure(median_5utr, median_cds, median_3utr,
                    utr_color=CONFIG$colors[2], cds_color=CONFIG$colors[1])
```

```{r cross_species_comparison}
# Compute median CDS lengths for T. brucei protein-coding genes
library('org.Tb927.tritryp.db')
tb_gene_ids <- keys(org.Tb927.tritryp.db, keytype='GID')
tb_genes <- AnnotationDbi::select(org.Tb927.tritryp.db, keys=tb_gene_ids,
                                  keytype='GID', columns=c('TYPE', 'GENESIZE'))
tb_median_cds <- median(tb_genes$GENESIZE[tb_genes$TYPE == 'proteincoding'])


# T. brucei gene structure UTR stats (Kolev et al., 2010)

# L. major Friedlin structure stats
# Median CDS size computed using all `gene` entries from 
#
# filepath  = '/path/to/TriTrypDB-27_LmajorFriedlin.gff'
# gff <- import.gff3(filepath)
# genes <- gff[gff$type == 'gene']
# median(as.numeric(genes$size))
#
lm_median_cds <- 1269
```
