## TriTryp gene structure comparison

```{r tbrucei_cds_length, message=FALSE, }
# Compute median CDS lengths for T. brucei protein-coding genes
# Get ID's for protein-coding genes
library(Trypanosoma.brucei.TREU927)
tb_gene_types <- AnnotationDbi::select(Trypanosoma.brucei.TREU927,
                                       keys=keys(Trypanosoma.brucei.TREU927,
                                                 keytype='GID'), keytype='GID',
                                       columns=c('TXTYPE'))

tb_protein_coding_genes <- tb_gene_types$GID[tb_gene_types$TXTYPE == 'mRNA']

tb_gff <- import.gff3('/cbcb/lab/nelsayed/ref_data/tbrucei_treu927/annotation/TriTrypDB-30_TbruceiTREU927.gff')
tb_genes <- tb_gff[tb_gff$type == 'gene']
tb_genes <- genes[genes$ID %in% tb_protein_coding_genes]

# Feb 18, 2017: GENESIZE no longer available in orgdb packages and TYPE
# renamed to TXTYPE in Bioconductor 3.4
                                  #keytype='GID', columns=c('TYPE', 'GENESIZE'))
#tb_median_cds <- median(tb_genes$GENESIZE[tb_genes$TYPE == 'proteincoding'])

# 1725 nt
tb_median_cds <- median(width(tb_genes))

# L. major Friedlin structure stats
# Median CDS size computed using all `gene` entries from TriTrypDB GFF
lm_median_cds <- 1269
```

Feature lengths for T. cruzi, T. brucei, and L. major.

From left to right:

- CDS
- 3'UTR
- Poly(A)-Polypyrimidine tract gap
- Polypyrimidine tract
- SL-Polypyrimidine tract gap
- 5'UTR
- CDS

```{r figure_X19_tritryp_gene_structure, fig.height=620/192, fig.width=1600/192, dev=c(opts_chunk$get('dev'), 'svglite'), fig.cap='**Figure X19** TriTryp gene structure comparison'}
tcruzi_lengths <- c(median_cds, median_3utr,
                    median(polypyr_combined$polya_dist), median_ppt,
                    median(polypyr_combined$sl_dist), median_5utr, median_cds)

# T. brucei gene structure lengths (Kolev et al., 2010)
tbrucei_lengths <- c(1242, 388, 81, 18, 43, 91, 1242)

# L. major gene structure lengths (Dillon et al., 2015)
lmajor_lengths <- c(1241, 729, 558, 21, 64, 547, 1241)

# combine into a single data frame
dat <- cbind(`T. brucei`=tbrucei_lengths, `T. cruzi`=tcruzi_lengths, 
             `L. major`=lmajor_lengths)

# plot properties
horizontal_pad <- 100
gene_width <- 180
gene_margin <- 20
plot_width <- max(colSums(dat)) + (2 * horizontal_pad)
plot_height <- (3 * gene_width) + (4 * gene_margin)

#
# Plot a single entry in a comparative gene structure plot
#
plot_gene_structure <- function(dat, i, plot_width, plot_height,
                                     gene_width, gene_margin, horizontal_pad) {
    # cds
    x0 <- (plot_width - colSums(dat)[i]) / 2
    x1 <- x0 + dat[1, i]

    # heights
    y0 <- gene_margin + (gene_width * (i - 1)) + (gene_margin * (i - 1))
    cds_y1 <- y0 + gene_width
    utr_y1 <- y0 + (gene_width / 2)
    other_y1 <- y0 + (gene_width / 4)

    # 3'utr, etc.
    x2 <- x1 + dat[2, i]
    x3 <- x2 + dat[3, i]
    x4 <- x3 + dat[4, i]
    x5 <- x4 + dat[5, i]
    x6 <- x5 + dat[6, i]
    x7 <- x6 + dat[7, i]

    rect(x0, y0, x1, cds_y1, col=CONFIG$colors[3])
    rect(x1, y0, x2, utr_y1, col=CONFIG$colors[1])
    rect(x2, y0, x3, other_y1, col=CONFIG$colors[2])
    rect(x3, y0, x4, other_y1, col=CONFIG$colors[4])
    rect(x4, y0, x5, other_y1, col=CONFIG$colors[2])
    rect(x5, y0, x6, utr_y1, col=CONFIG$colors[1])
    rect(x6, y0, x7, cds_y1, col=CONFIG$colors[3])
}

# create plot
#plot(c(0, plot_width), c(0, plot_height * 3), type='n', 
plot(c(0, plot_width), c(0, plot_height), type='n', 
     xlab='', ylab='', xaxt='n', yaxt='n', mar=c(4, 12, 1, 1))

plot_gene_structure(dat, 1, plot_width, plot_height, gene_width,
                         gene_margin, horizontal_pad)
plot_gene_structure(dat, 2, plot_width, plot_height, gene_width,
                         gene_margin, horizontal_pad)
plot_gene_structure(dat, 3, plot_width, plot_height, gene_width,
                         gene_margin, horizontal_pad)

ytick1 <- gene_margin + (gene_width / 2)
ytick2 <- ytick1 + gene_margin + gene_width
ytick3 <- ytick2 + gene_margin + gene_width

axis(2, labels=colnames(dat), at=c(ytick1, ytick2, ytick3), tick=FALSE,
     cex.axis=0.75, las=1)
```

```{r table_1}
table_1 <- dat[1:6,]
rownames(table_1) <- c('CDS', "3' UTR", 'Poly(A) - PolyPy distance', 'PolyPy tract', 
                       'SL - PolyPy distance', "5' UTR")

# reorder columns and display
table_1 <- table_1[c(6,1,2,3,4,5),]
xkable(table_1, caption='**Table 1** TriTryp comparative gene structure.')
```
