## Average gene structure

```{r figure_02, fig.height=250/96, fig.cap="**Figure 2**: Average 5'UTR, CDS, and 3′ UTR lengths across all development stages."}
# Summary of gene structure
polypyrimidine_tracts <- polypyrimidine_tracts %>%
    mutate(length=end - start)
pp_tract_summary <- polypyrimidine_tracts %>%
    group_by(stage) %>% 
    summarise(median=median(length, na.rm=TRUE))

median_5utr <- (utr5_summary %>% filter(stage == 'combined'))$median
median_cds  <- median(as.numeric(genes$size))
median_3utr <- (utr3_summary %>% filter(stage == 'combined'))$median
median_ppt  <- (pp_tract_summary %>% filter(stage == 'combined'))$median

plot_gene_structure(median_5utr, median_cds, median_3utr,
                    utr_color=CONFIG$colors[2], cds_color=CONFIG$colors[1])
```

```{r, results='asis', message=FALSE}
# create a data frame to store gene-matched lengths
matched_lengths <- data.frame()

# compute median mRNA length for all genes for which we have sufficient
# information
for (gene_id in utr3_stats_combined$gene) {
    # skip genes for which we don't know both UTR lengths
    if (!gene_id %in% utr5_stats_combined$gene) {
        next
    }

    # get length of each component and add entry to dataframe
    matched_lengths <- rbind(matched_lengths, c(
        (utr5_stats_combined %>% filter(gene == gene_id))$length,
        (utr3_stats_combined %>% filter(gene == gene_id))$length,
        width(genes[genes$ID == gene_id])
    ))
}

cat(sprintf('- Median mRNA length: %d nt\n',
            as.integer(median(rowSums(matched_lengths)))))

# average proportion of mRNA contributed by each portion
utr5_prop <- 100 * mean(matched_lengths[,1] / rowSums(matched_lengths))
utr3_prop <- 100 * mean(matched_lengths[,2] / rowSums(matched_lengths))
cds_prop  <- 100 * mean(matched_lengths[,3] / rowSums(matched_lengths))

cat(sprintf('- 5\'UTR: %0.2f %%\n', utr5_prop))
cat(sprintf('- 3\'UTR: %0.2f %%\n', utr3_prop))
cat(sprintf('- CDS: %0.2f %%\n\n', cds_prop))
```

```{r cross_species_comparison, message=FALSE}
# Compute median CDS lengths for T. brucei protein-coding genes
library('org.Tb927.tritryp.db')
tb_gene_ids <- keys(org.Tb927.tritryp.db, keytype='GID')
tb_genes <- AnnotationDbi::select(org.Tb927.tritryp.db, keys=tb_gene_ids,
                                  keytype='GID', columns=c('TYPE', 'GENESIZE'))
tb_median_cds <- median(tb_genes$GENESIZE[tb_genes$TYPE == 'proteincoding'])


# T. brucei gene structure UTR stats (Kolev et al., 2010)

# L. major Friedlin structure stats
# Median CDS size computed using all `gene` entries from 
#
# filepath  = '/path/to/TriTrypDB-27_LmajorFriedlin.gff'
# gff <- import.gff3(filepath)
# genes <- gff[gff$type == 'gene']
# median(as.numeric(genes$size))
#
lm_median_cds <- 1269
```

## Average GC- and CT-richness

```{r table_s06, results='asis'}
# function to compute proportion of a nucleotide for a collection of sequences
nt_proportion <- function (seqs) { 
    # Exclude any N's
    seqs <- gsub('N', '', seqs)

    # feature lengths
    seq_lengths <- unlist(lapply(seqs, nchar))

    # measure proportion of each nucleotide, for each feature
    sapply(c('A', 'C', 'G', 'T'), function (nt) { 
        str_count(seqs, nt) / seq_lengths 
    })
}

# intergenic region composition
intergenic_seqs <- (intercds_regions %>% filter(stage == 'combined'))$intergenic_seq
intergenic_comp <- nt_proportion(intergenic_seqs)

# 5' and 3'UTR composition
utr5_comp <- nt_proportion(utr5_stats_combined$seq)
utr3_comp <- nt_proportion(utr3_stats_combined$seq)

# Drop any features for which there were only N's (rare)
utr5_comp <- utr5_comp[complete.cases(utr5_comp),]
utr3_comp <- utr3_comp[complete.cases(utr3_comp),]

# CDS composition
cds_comp <- nt_proportion(as.character(cds_fasta))

# Genome composition
genome_comp <- nt_proportion(as.character(fasta))

# data frame of sequence compositions, by feature
table_s06 <- data.frame(
    utr5=apply(utr5_comp, 2, median),
    cds=apply(cds_comp, 2, median),
    utr3=apply(utr3_comp, 2, median),
    intergenic=apply(intergenic_comp, 2, median),
    genome=apply(genome_comp, 2, median)
)

# GC richness
table_s06 <- rbind(table_s06, GC=table_s06[2,] + table_s06[3,])

kable(table_s06, caption="**Table S6** Median GC- and CT-richness for gene features.")
```
