### Differences in trans-splicing acceptor site usage across developmental stage

```{r figure_x_stage-specific_5utr_lengths, fig.cap="**Figure SX** 5'UTR length across developmental stage.", warning=FALSE}
for (s1_name in stages) {
    for (s2_name in stages) {
        # skip combined site dataframes and self comparisons
        if (s1_name == 'combined' || s2_name == 'combined' || s1_name == s2_name) {
            next
        }
        
        # create cross-stage dataframe and plot UTRs with variables lengths
        # across developmental stage
        dat <- create_utr_comparison_df(sl_sites, s1_name, s2_name)
        print(plot_diff_utrs(dat, 'SL'))
    }
}
```

### Differences in polyadenylation site usage across developmental stage

```{r figure_x_stage-specific_3utr_lengths, fig.cap="**Figure SX** 3′ UTR length across developmental stage.", warning=FALSE}
for (s1_name in stages) {
    for (s2_name in stages) {
        # skip combined site dataframes and self comparisons
        if (s1_name == 'combined' || s2_name == 'combined' || s1_name == s2_name) {
            next
        }
        
        # create cross-stage dataframe and plot UTRs with variables lengths
        # across developmental stage
        dat <- create_utr_comparison_df(polya_sites, s1_name, s2_name)
        print(plot_diff_utrs(dat, 'Poly(A)'))
    }
}
```
